services:
  fastapi:
    image: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./:/app
    env_file:
      - .env
    command: >
      sh -c "if [ \"$ENVIRONMENT\" = \"development\" ]; then
              pip install --user -r requirements.txt &&
              alembic upgrade head &&
              uvicorn app.main:app --host 0.0.0.0 --port 8010 --reload --reload-dir /app/app;
            else
              alembic upgrade head &&
              gunicorn --bind 0.0.0.0:8010 -k uvicorn.workers.UvicornWorker app.main:app;
            fi"

    networks:
      # - sales_network
      - postgrest_default
    restart: unless-stopped

networks:
  postgrest_default:
    external: true  # Red ya creada por Docker
