"""Adding Datetime attributes to the Category model 

Revision ID: 406886b8bd5f
Revises: 0feaaaf52e2a
Create Date: 2025-08-14 13:06:39.555389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406886b8bd5f'
down_revision: Union[str, None] = '0feaaaf52e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], referent_schema='sales_management', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_category_id_fkey'), 'category', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('last_update')
        batch_op.drop_column('created')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
