"""Adding Code attribute to the Product model

Revision ID: 7168d4e45fa2
Revises: a97e2a053f56
Create Date: 2025-08-18 19:30:13.816639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7168d4e45fa2'
down_revision: Union[str, None] = 'a97e2a053f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('product_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], referent_schema='sales_management', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_category_id_fkey'), 'category', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
