"""Adding Datetime attributes to the Product model

Revision ID: a97e2a053f56
Revises: 406886b8bd5f
Create Date: 2025-08-18 12:26:32.546796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97e2a053f56'
down_revision: Union[str, None] = '406886b8bd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        # add temporary column settings to nullable
        batch_op.add_column(sa.Column('base_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('internal_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('stock_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        # add temporary column settings to nullable
        batch_op.add_column(sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_constraint(batch_op.f('product_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], referent_schema='sales_management', ondelete='SET NULL')
    
    # update existing records with default values
    op.execute(
        "UPDATE product SET "
        "base_currency = 'MXN', "
        "internal_code = '00001', "
        "stock_min = 0, "
        "active = true"
    )

    # reverting column settings to non-nullable
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('base_currency', nullable=False)
        batch_op.alter_column('internal_code', nullable=False)
        batch_op.alter_column('stock_min', nullable=False)
        batch_op.alter_column('active', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_category_id_fkey'), 'category', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('last_update')
        batch_op.drop_column('created')
        batch_op.drop_column('active')
        batch_op.drop_column('stock_min')
        batch_op.drop_column('internal_code')
        batch_op.drop_column('base_currency')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
